config:
    shim:
        'flotr2':
            deps:
                - 'jquery'

    paths:
        'flotr2': 'bundles/orochart/lib/flotr2/flotr2.amd.js'
        'bean': 'bundles/orochart/lib/flotr2/bean.js'
        'orochart/js/chart_form': 'bundles/orochart/js/chart_form.js'
        'orochart/js/data_formatter': 'bundles/orochart/js/data_formatter.js'
        'orochart/js/flotr2/funnel': 'bundles/orochart/js/flotr2/funnel.js'
        'orochart/js/charts/bar_chart': 'bundles/orochart/js/charts/bar_chart.js'
        'orochart/js/charts/pie_chart': 'bundles/orochart/js/charts/pie_chart.js'
        'orochart/js/charts/flow_chart': 'bundles/orochart/js/charts/flow_chart.js'
        'orochart/js/charts/line_chart': 'bundles/orochart/js/charts/line_chart.js'
