parameters:
    oro_chart.config_provider.class:    Oro\Bundle\ChartBundle\Model\ConfigProvider
    oro_chart.form.type.settings.class: Oro\Bundle\ChartBundle\Form\Type\ChartSettingsType
services:
    oro_chart.config_provider:
        class: %oro_chart.config_provider.class%
        arguments:
            - []

    oro_chart.form.type:
        class: %oro_chart.form.type.settings.class%
        arguments:
            - @oro_chart.config_provider
        tags:
            - { name: form.type, alias: oro_config_form_type }
