oro_chart:
    line_chart:
        label: Line Chart
        data_schema:
          - name: label
            label: Category (X axis)
            required: true
          - name: value
            label: Value (Y axis)
            required: true
        settings_schema:
          - name: connect_dots_with_line
            label: Connect line with dots
            type: boolean
            options: { required: true }
        default_settings: ~
        template: OroChartBundle:Chart:lineChart.html.twig
