oro_chart:
    line_chart:
        label: oro.chart.line_chart.label
        data_schema:
          - name: label
            label: oro.chart.line_chart.params.label
            required: true
          - name: value
            label: oro.chart.line_chart.params.value
            required: true
            filter: number # filter for fields, see query_designer.yml filter section
        default_settings:
            connect_dots_with_line: true
            available_in_reports: true
            chartColors: ['#ACD39C', '#BE9DE2', '#6598DA', '#ECC87E', '#A4A2F6', '#6487BF', '#65BC87', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
        template: OroChartBundle:Chart:line.html.twig
    bar_chart:
        label: oro.chart.bar_chart.label
        data_schema:
          - name: label
            label: oro.chart.bar_chart.params.label
            required: true
          - name: value
            label: oro.chart.bar_chart.params.value
            required: true
            filter: number # filter for fields, see query_designer.yml filter section
        default_settings:
            available_in_reports: true
            chartColors: ['#ACD39C', '#BE9DE2', '#6598DA', '#ECC87E', '#A4A2F6', '#6487BF', '#65BC87', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
        template: OroChartBundle:Chart:bar.html.twig
    pie_chart:
        label: oro.chart.pie_chart.label
        data_schema:
          - name: label
            label: oro.chart.pie_chart.params.label
            required: true
          - name: value
            label: oro.chart.pie_chart.params.value
            required: true
            filter: number # filter for fields, see query_designer.yml filter section
        default_settings:
            fraction_input_data_field: value
            fraction_output_data_field: fraction
            chartColors: ['#ACD39C', '#BE9DE2', '#6598DA', '#ECC87E', '#A4A2F6', '#6487BF', '#65BC87', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
        data_transformer: oro_chart.data_transformer.pie_chart
        template: OroChartBundle:Chart:pie.html.twig
    flow_chart:
        label: oro.chart.flow_chart.label
        data_schema:
          - name: label
            label: oro.chart.flow_chart.params.label
            required: true
          - name: value
            label: oro.chart.flow_chart.params.value
            required: true
            filter: number # filter for fields, see query_designer.yml filter section
          - name: isNozzle
            label: oro.chart.flow_chart.params.is_nozzle
            required: false
            filter: boolean # filter for fields, see query_designer.yml filter section
        default_settings:
            chartColors: ['#ACD39C', '#BE9DE2', '#6598DA', '#ECC87E', '#A4A2F6', '#6487BF', '#65BC87', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
        template: OroChartBundle:Chart:flow.html.twig
